### PR TITLE
Search in submenu chip or cpu for vars

### PR DESCRIPTION
**Pull request by straccio**
Using new Arduino IDE and ATTinyCore board module he need to search var
various vars not in cpu submenu but in chip. Changed the makefile in
order to search chip or cpu using regular expression.

### CODE REVIEW

**Comment by sej7278** [comment]
looks like it should work, seems more like a bug in the attiny core, why change from cpu to chip?

**Comment by straccio** [comment]
i don't know why :(

**Comment by sej7278** [comment]
:+1: can we merge this?

**Comment by straccio** [comment]
yes you can ^^

**Comment by sudar** [comment]
@sej7278 Didn't see your edit. I guess it's fine..

**Pull request merged**
