### PR TITLE
Fix Travis CI, add SAMD test support, support GNU grep on macOS

### LINKED ISSUE #625: Multiple toolchains cause makefile failure
It appears that if more than one directories exist in the below directory, it causes ARM_TOOLS_DIR to contain multiple space separated paths and the makefile to fail

Sam.mk:165 `$(ARDUINO_PACKAGE_DIR)/$(ARDMK_VENDOR)/tools/$(TOOL_PREFIX)-gcc`
https://github.com/sudar/Arduino-Makefile/blob/e870443f4824cbbcd560f500c6072012dd668f62/Sam.mk#L165

I discovered this as my directory reference contained: "4.8.3-2014q1" and "7-2017q4"

### PR DESCRIPTION
**Pull request by tuna-f1sh**
Content as subject, includes fix #625. Includes @sej7278's Python 3 branch. BSD `grep` was creating some warnings parsing boards.txt that were annoying!

### CODE REVIEW

**Comment by tuna-f1sh** [comment]
Now includes https://github.com/sudar/Arduino-Makefile/pull/630 (manual as @osamuaoki's branch has gone awol).

**Comment by sej7278** [comment]
:+1:

**Comment by sej7278** [comment]
> Now includes #630 (manual as @osamuaoki's branch has gone awol).

i'm still not 100% sure about that one.

in the debian package it doesn't work as `ARDMK_DIR` isn't defined anywhere and even if you define it, you can't build the examples as you can't write to `/usr/share/doc/arduino-mk/examples`

at least with `../../Arduino.mk` it works for a git checkout.

seems like the debian package would require the user to copy the examples to their sketchbook directory and define `ARDMK_DIR` in their local Makefile, like:

```
ARDMK_DIR = /usr/share/arduino
#ARDMK_DIR = ../../
BOARD_TAG = uno
include $(ARDMK_DIR)/Arduino.mk
```

at which point setting `ARDMK_DIR` seems a bit pointless and you may as well stick with:

```
BOARD_TAG = uno
include /usr/share/arduino/Arduino.mk
```

so maybe we should drop that PR?

**Comment by tuna-f1sh** [comment]
I thought the thinking was that since the README mandates that `ARDMK_DIR` should be defined by the user, the examples failing helps to ensure this?

Could add in a catch to check for `ARDMK_DIR` and error if undefined with helpful hint or define it to as it was prior:

```
ifdef ARDMK_DIR
    include $(ARDMK_DIR)/Arduino.mk
else
    $(info ! Using project relative ARDMK_DIR, please define environment variable ARDMK_DIR as Arduino-Makefile installation directory for external use)
    include ../../Arduino.mk
endif
```

**Comment by sej7278** [comment]
where would you put that though - in every example?

**Comment by tuna-f1sh** [comment]
Yes would be quite messy. It does make the example Makefiles better for copying into a project however. 

Don't mind, can just remove it and revert back to relative path for all the Makefiles.

**Comment by sej7278** [comment]
yeah if you can revert it back to ../../ we can look at it again afterwards maybe

**Comment by tuna-f1sh** [comment]
It's gone.

**Comment by tuna-f1sh** [comment]
Have you had chance to review @sudar ? Would be good to get a 2.0 release after this push to fix the Python 3 shebang problem.

**Comment by sudar** [comment]
@tuna-f1sh 

I finally got some time this weekend to test it.

I will merge it mostly by tomorrow.

**Comment by sudar** [comment]
Sorry guys, what I thought will take just 2 days ended up being 2 weeks. Finally I was able to test the fix and have just merged it.

Thanks @sej7278 @tuna-f1sh and others who helped to get this done.

**Pull request merged**
