### PR TITLE
 Add OpenCR.mk for OpenCR 1.0 board example sketch

### PR DESCRIPTION
**Pull request by Dukejung**
This is OpenCR makefile to build sketches for Robotis OpenCR 1.0 from the command line.

OpenCR1.0 is a board for ROS embedded system made by robotis company that also made OpenCM.
(Detailed explanation for OpenCR1.0 : http://emanual.robotis.com/docs/en/parts/controller/opencr10/)

Arduino IDE and additional OpenCR package is needed to build OpenCR sketches. By following the procedure described in below link, you can add OpenCR package in Arduino IDE via board manager.
http://emanual.robotis.com/docs/en/parts/controller/opencr10/#arduino-ide

Also blink example for OpenCR 1.0 is uploaded together. 

I tested this makefile with Robotis turtlebot3 tank example.
https://www.youtube.com/watch?v=vndnwpVEpVE

### CODE REVIEW

**Comment by sej7278** [comment]
:+1:

**Comment by sej7278** [comment]
@sudar how about merging this new platform?

the install procedure looks horrible (bunch of 32-bit libs plus boardmanager package) but if the user is willing to do that....

**Comment by sudar** [comment]
@sej7278 

I am fine as long as we don't break any of the existing stuff and if the new platform works in Arduino.

Just checked and the code doesn't touch any of the existing things and also the platform works in Arduino. So I just merged it.

Let's plan to make a new release soon.

**Comment by sudar** [comment]
@Dukejung 

Thanks for your contribution. We just merged the PR.

**Pull request merged**
