### PR TITLE
Added some more advanced tests to Travis CI

### PR DESCRIPTION
**Pull request by sej7278**
Better than just "make clean && make". 

Tested on Arduino, Teensy and chipKIT, they all provide the functions called.

Could probably do with adding IDE 1.6.4 tests next (alongside 1.0.6 not instead of).

### CODE REVIEW

**Comment by sudar** [comment]
@sej7278 Thanks.

I am just waiting for Travis CI to complete before merging this.

**Comment by sej7278** [comment]
well the AVR C example failed as it skips the assembly stage (no core to link) but Travis_CI still passed it, so not sure what use CI is!

```
make: *** No rule to make target `build-atmega16/BlinkInAVRC.s', needed by `generate_assembly'.  Stop.
```

**Comment by sudar** [comment]
Hmm.. That's strange.

Do you me hold of merging this PR, till we figure it out?

**Comment by sej7278** [comment]
trying again, but i've got to do a couple more commits to check it does break when it should, then i'll clean it up.

**Comment by sej7278** [comment]
ok i checked it does break when expected to now. new PR is at #355 should be ok to merge

**Pull request closed without merging**
