### PR TITLE
Update Arduino.mk

### PR DESCRIPTION
**Pull request by thalesmaoa**
Added some break lines.

Just want to compile the program without arduino lib, no no_core flag does not let know processor size.

### CODE REVIEW

**Comment by sudar** [comment]
@sej7278 What are you thoughts on this?

@thalesmaoa Can you also please update HISTORY.md file with a brief summary of the change?

**Comment by sej7278** [comment]
i've no idea what its supposed to do lol

**Comment by thalesmaoa** [comment]
I don't know really if it is the best way to fix a bug, but I will explain
what happen and you can figure if it is a good merge.


I've made a standalone program to use with an arduino based processor. When
I use your awesome makefile, it work ok, but it also compile arduino libs,
but I don't use them. I do not even include them.

I realized that no_core = yes and mcu = atmega2560 flag keeps arduino lib
out of compilation, but at the end throw a bug message.

This message is what I was trying to fix.

1) Just added breadlines to the end of echo

2) When I use mcu = 2560 it already knows my processor size, because it
still tells me how full I am. In my case, 18%. But in the end, it tells me
that it doesn't. So I took out HEX_MAXIMUM_SIZE variable so the message
doesn't start.

Best regards
​

**Comment by sej7278** [comment]
seems odd though, as we put all of the calls to PARSE_BOARD inside the NO_CORE block as if you're not using the arduino core, you also wouldn't have a boards.txt file to parse.

surely the solution to your problem would be to put ```HEX_MAXIMUM_SIZE=258048``` in your Makefile?

also you've duplicated that code block, rather than moving it.

**Comment by thalesmaoa** [comment]
You are right, but I do use arduino core. It was just my workaround to no
compile arduino libs.

Sorry to duplicate, I didn't notice, but it is not a good solution indeed.

-
Thales Alexandre Carvalho Maia


2016-03-01 8:50 GMT-03:00 Simon John <notifications@github.com>:

**Comment by sej7278** [comment]
so you're using the arduino core but none of the libraries, and want to not compile the built-in libraries?

that's issue #29 which is the same way the ide does it - the libraries are compiled so its a bit slow, but they're not linked so take up no memory in the final hex.

**Comment by thalesmaoa** [comment]
That is the reason why I quit IDE as well. :)

I know it does not increase hex size, but pollute my make output and
difficult the tracking of warning messages.
It is not a big deal, just a simple solution.

-
Thales Alexandre Carvalho Maia


2016-03-01 9:47 GMT-03:00 Simon John <notifications@github.com>:

**Comment by sej7278** [comment]
well if you don't mind it compiling the unused libraries and just want it to be quiet in the output then probably setting ```HEX_MAXIMUM_SIZE=258048``` is the best way, rather than your PR which could cause problems for people who really don't want to use the arduino core or boards.txt at all.

[ARDUINO_QUIET](https://github.com/sudar/Arduino-Makefile/blob/master/arduino-mk-vars.md#arduino_quiet) may be of some interest to you also

**Comment by sudar** [comment]
@thalesmaoa 

Thanks for the PR.

Please see @sej7278's suggestion above.

I am closing this without merging. But feel free to re-open if you have additional information.

**Pull request closed without merging**
