### PR TITLE
Fix regression: PARSE_BOARD chops off flags which contain '=' signs

### PR DESCRIPTION
**Pull request by stv0g**
See #601

### CODE REVIEW

**Comment by sudar** [comment]
@sej7278 

What are your thoughts on this?

I checked the diff and it looks good to me, but since I don't have a non-Arduino board I am not sure if it causes any other issues.

**Comment by stv0g** [comment]
Hi @sej7278 @sudar 

any updates on this PR?

Cheers,
Steffen

**Comment by sej7278** [comment]
doesn't look like it'll cause problems and would be nice to remove duplicated code from sam.mk :+1:

**Comment by sudar** [comment]
@stv0g 

Thanks for the PR. Just merged it.

**Pull request merged**
